### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by sKanoodle** [ZombieAlex/mfcauto.py#3]
I experimented a bit with mfcauto to get tags while querying for online models. In the example in tests/findModels.py, all tags were set to None. I looked a bit into the code and saw the event FCTYPE.TAGS. I wrote a function to pass to that to look what the output would be, and _knownmodels now had objects with tags (and no session or name) and objects with session and name (but no tags). I guess there is something wrong with merging them together.
(Might be that "bestsession"['uid'] is a string for tag objects and an int for the others)

Anyway, I don't know what the expected behavior is here, but if this is all indeed expected, you should at least include this script in the tests, to spare other people who want tags some time.

<details>
<summary>click to view code</summary>

```python
import requests
import mfcauto
import threading

SERVER_CONFIG_URL = 'http://www.myfreecams.com/_js/serverconfig.js'

def get_online_models():
    '''returns a dictionary of all online models in free chat'''
    server_config = requests.get(SERVER_CONFIG_URL).json()
    servers = server_config['h5video_servers'].keys()
    models = {}
    models_lock = threading.Lock()

    def on_tags(_):
        '''function for the TAGS event in mfcclient'''
        nonlocal models

        #locking to prevent from disconnecting too early
        with models_lock:
            #test for data in models. Data in models means that we
            #already had this function running and we can disconnect safely
            if models:
                client.disconnect()
                return

            #merging tags and models (needed due to a possible bug in mfcauto)
            all_results = mfcauto.Model.find_models(lambda m: True)
            for element in all_results:
                uid = int(element.uid)
                if uid not in models.keys():
                    models[uid] = Model(element)
                    continue
                model = models[uid]
                models[uid] = model.merge_tags(element)
                #at this point we have a merged object, so we can filter
                if model.session['vs'] != mfcauto.STATE.FreeChat or str(model.session['camserv']) not in servers:
                    models.pop(uid)

    #we dont want to query the models in CLIENT_MODELSLOADED, because we are
    #missing the tags at this point. Rather query everything on TAGS
    client = mfcauto.SimpleClient()
    client.on(mfcauto.FCTYPE.CLIENT_MODELSLOADED, lambda: None)
    client.on(mfcauto.FCTYPE.TAGS, on_tags)
    client.connect()

    return models

class Model():
    '''custom Model class to preserve the session information'''
    def __init__(self, model):
        self.name = model.nm
        self.uid = model.uid
        self.tags = model.tags
        #vs info will be lost
        self.session = model.bestsession

    def __repr__(self):
        return '{{"name": {}, "uid": {}, "tags": {}, "session": {}}}'.format(
            self.name, self.uid, self.tags, self.session)

    def merge_tags(self, model):
        '''merges tags into a model or vice versa and returns new object'''
        base = self if self.tags is None else model
        base.tags = self.tags if self.tags is not None else model.tags
        return base

print(get_online_models())
```

**Comment by ZombieAlex** [comment]
Hey, thanks for the report. That was the issue causing tags to be merged to invalid models.  uid must always be an int

> Might be that "bestsession"['uid'] is a string for tag objects and an int for the others

I fixed that issue, however you still won't be seeing the behavior you really wanted. Tags will not be filled in yet if you merely wait for CLIENT_MODELSLOADED. It's worse than that actually. The findModels.py example in my repo will never work, because age details aren't merged into models when CLIENT_MODELSLOADED fires either.

The main problem is that MFC changed key parts of their protocol back in April. On connection, they now send a limited set of information about all online models with the core details like their status, room topic, and camserv. Tags come in later, asynchronously, and other details like age may never come at all, if you don't join a model's room or otherwise interact with her.

I chose to fire MODELSLOADED after the initial status of all models is completed, because many use cases only care about who is online or on cam and waiting for tags or other details would slow down those scenarios. But I'm open to adding another TAGSLOADED event if that's a scenario you care about. Shouldn't be too hard.

For age and other details, one currently guaranteed way of getting those is to use Client.query_user. My test/userLookup.py has an example of that. But ultimately I'm at the mercy of what MFC's servers provide.

Hope that helps.
